config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "admin" do
    resources :sublibraries
    resources :users
    resources :patron_status_permissions
    resources :permission_values
    resources :permissions
    resources :patron_statuses
    resources :application_details

    get 'clear_patron_data' => 'users#clear_patron_data'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    match '/logout', to: 'sessions#destroy', as: :logout, via: [:post]
    match '/login', to: 'users/omniauth_callbacks#passthru', as: :login, via: [:post]
  end

  patch 'permissions/update_order' => 'permissions#update_order'
  patch 'patron_status_permissions/update_multiple' => 'patron_status_permissions#update_multiple'

  get 'search' => 'privileges#search', as: :search
  get 'patrons/:id' => 'privileges#show_patron_status', as: :patron
  get 'patrons(.:format)' => 'privileges#index_patron_statuses', as: :patrons

  root to: 'privileges#index_patron_statuses'
end

app/controllers/patron_statuses_controller.rb
# The controller handles the class that manages information for each patron status
class PatronStatusesController < ApplicationController
  before_action :authenticate_admin

  # GET /patron_statuses
  # GET /patron_statuses.json
  def index
    @patron_status_search = patron_status_search

    respond_to do |format|
      format.json do
        render json: @patron_status_search.results,
               layout: false and return
      end
      format.html
    end
  end

  # GET /patron_statuses/1
  def show
    @patron_status = PatronStatus.find(params[:id])
    @permissions = Permission.visible.where(from_aleph: false)
    @permission_values = PermissionValue.where(permission_code: params[:permission_code])
    @sublibraries = Sublibrary.search{ order_by(:sort_text, :asc) }.results
    @sublibrary = sublibrary
    @patron_status_permission = PatronStatusPermission.new
    @patron_status_permissions = patron_status_permissions
  end

  # GET /patron_statuses/new
  def new
    @patron_status = PatronStatus.new
  end

  # GET /patron_statuses/1/edit
  def edit
    @patron_status = PatronStatus.find(params[:id])
  end

  # POST /patron_statuses
  def create
    @patron_status = PatronStatus.new

    @patron_status.code = "#{prefix}#{patron_status_params[:code]}"
    @patron_status.web_text = patron_status_params[:web_text]
    @patron_status.keywords = patron_status_params[:keywords]
    @patron_status.from_aleph = (patron_status_params[:from_aleph]) ? patron_status_params[:from_aleph] : false
    @patron_status.under_header = patron_status_params[:under_header] unless patron_status_params[:under_header].blank?
    @patron_status.id_type = patron_status_params[:id_type]

    respond_to do |format|
      if @patron_status.save
        flash[:notice] = t('patron_statuses.create_success')
        format.html { redirect_to(@patron_status) }
      else
        #If failed, set the code back to user-entered code, without prefix
        @patron_status.code = patron_status_params[:code]
        format.html { render action: "new" }
      end
    end
  end

  # PUT /patron_statuses/1
  # PUT /patron_statuses/1.js
  def update
    @patron_status = PatronStatus.find(params[:id])
    @patron_statuses = patron_status_search.results

    respond_to do |format|
      if @patron_status.update_attributes(patron_status_params)
        flash[:notice] =  t('patron_statuses.update_success')
        format.html { redirect_to @patron_status }
        format.js { render nothing: true } if request.xhr?
      else
        format.html { render action: "edit" }
        format.js { render nothing: true } if request.xhr?
      end
    end
  end

  # DELETE /patron_statuses/1
  def destroy
    @patron_status = PatronStatus.find(params[:id])
    @patron_status.destroy

    respond_to do |format|
      format.html { redirect_to(patron_statuses_url) }
    end
  end

  # Local implementation of parent sort_column function
  def sort_column
    super "PatronStatus", ""
  end
  helper_method :sort_column

  private

  def patron_status_search
    @patron_status_search ||= Privileges::Search::PatronStatusSearch.new(**patron_status_search_params)
  end

  def patron_status_search_params
    params.permit(:q, :sort, :direction, :page, :patron_status_code, :sublibrary_code)
      .select{|k,v| v.present? }.to_h.symbolize_keys.merge(admin_view: admin_view?)
  end

  # Shortcut for retrieving sublibrary object
  def sublibrary
    @sublibrary ||= ::Sublibrary.find_by_code(params[:sublibrary_code]) if params[:sublibrary_code].present?
  end

  def patron_status_params
    if params[:patron_status].present?
      params.require(:patron_status).permit(:web_text, :keywords, :under_header, :id_type, :description, :visible, :from_aleph, :code)
    else
      {}
    end
  end

  # Retreive this @patron_status patron_status_permissions with additional information joined in for display
  def patron_status_permissions
    @patron_status_permissions ||= @patron_status.patron_status_permissions.joins(permission_value: :permission).where(permissions: {visible: true}, sublibrary_code: sublibrary.code).order("permissions.sort_order asc") unless sublibrary.nil?
  end

  def prefix
    #This handles local creation of patron statuses by adding a namespace prefix, namely nyu_ag_noaleph_
    @prefix ||= (!params[:patron_status][:from_aleph].nil?) ? local_creation_prefix : ""
  end
end

app/views/patron_statuses/_form.html.erb
<%= form_for(@patron_status) do |f| %>
  <% if @patron_status.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@patron_status.errors.count, "error") %> prohibited this patron status from being saved:</h2>

      <ul>
      <% @patron_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :code %>
    <%= f.text_field :code, :disabled => locals[:disable_code_field], class: "form-control" %>
  </div>
  <% if @patron_status.from_aleph? %>
  <div class="form-group">
    <%= f.label :original_text %>
    <%= f.text_field :original_text, :disabled => true, class: "form-control" %>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :web_text %>
    <%= f.text_field :web_text, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :keywords %> <%= tooltip_tag(icon_tag(:info), "Enter a comma-delimited list of keywords to aid in the patron status search.") %>
    <%= f.text_field :keywords, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :under_header, "Grouping" %>
    <%= f.text_field :under_header, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :id_type %>
    <%= f.text_field :id_type, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :rows => 3, class: "form-control" %>
  </div>
  <div class="actions">
    <button type="submit" class="btn btn-default">Save changes</button>
  </div>

<% end %>

<br />

app/views/patron_statuses/_patron_statuses.html.erb
<p><%= page_entries_info_sunspot @patron_status_search %></p>

<%= paginate @patron_status_search.hits, theme: "bootstrap" %>

<table class="table table-bordered table-striped">
  <thead>
  <tr>
		<th><%= sortable "under_header", "Grouping"%></th>
		<th><%= sortable "code"%></th>
		<th><%= sortable "original_text"%></th>
		<th><%= sortable "web_text"%></th>
		<th><%= sortable "from_aleph", "From Aleph?"%></th>
		<th colspan="4">Actions</th>
  </tr>
  </thead>
  <tbody>
<% @patron_status_search.results.each do |patron_status| %>
	<tr class="<%=hidden_class(patron_status)%>">
		<td><%=h patron_status.under_header.html_safe unless patron_status.under_header.nil? %></td>
		<td><%=h word_break(patron_status.code) %></td>
		<td><%=h patron_status.original_text %></td>
		<td><%=h patron_status.web_text.html_safe unless patron_status.web_text.nil? %></td>
		<td><%=h patron_status.from_aleph %></td>
		<td class="actions"><%= link_to 'Show', patron_status %></td>
		<td class="actions"><%= link_to 'Edit', edit_patron_status_path(patron_status) %></td>
		<td class="actions"><%= link_to_unless(patron_status.from_aleph?, 'Destroy', patron_status, data: { confirm: 'Are you sure?' }, :method => :delete) %></td>
		<td class="actions"><%= link_to "#{(patron_status.visible) ? 'Hide' : 'Reveal' }", patron_status_path(patron_status, { controller: params[:controller], action: params[:action], :patron_status => {:visible => !patron_status.visible} }), :method => :put, :remote => true, :class => "toggle_visible" %></td>
	</tr>
<% end %>
  </tbody>
</table>

<%= paginate @patron_status_search.hits, theme: "bootstrap" %>

app/views/patron_statuses/_permission_values.html.erb
<%= collection_select(:patron_status_permission, :permission_value_id, @permission_values, :id, :web_text, {:include_blank => "Select a permission value"}) %>

app/views/patron_statuses/_permissions.html.erb
<% if @sublibrary %>

<h3><%= sublibrary_text(@sublibrary) %></h3>
<div id="permissions_<%=@sublibrary.code%>">
  <%= form_tag({:controller => "patron_status_permissions", :action => "update_multiple"}, :method => :patch, :remote => true, :id => "edit_patron_status_permissions") do %>

	<%= hidden_field_tag "patron_status_permission[patron_status_code]", @patron_status.code %>
	<%= hidden_field_tag "patron_status_permission[sublibrary_code]", @sublibrary.code %>
	<%= hidden_field_tag "patron_status_permission[from_aleph]", 0 %>

	<table class="table table-bordered table-striped">
		<thead>
		  <tr>
  			<th>Permission</th>
  			<th>Value</th>
  			<th colspan="2">Actions</th>
  		</tr>
		</thead>
		<tbody>
		  <% @patron_status_permissions.each do |ps_perm| %>
      <tr class="<%=hidden_class(ps_perm)%>">
        <td><%= ps_perm.permission.web_text %></td>
        <td><%= get_permission_value(ps_perm) %></td>
        <td class="actions"><%= link_to_unless(ps_perm.from_aleph?, 'Destroy', ps_perm, data: { confirm: 'Are you sure?' }, :method => :delete) %></td>
     	  <td class="actions"><%= link_to "#{(ps_perm.visible) ? 'Hide' : 'Reveal' }", patron_status_permission_path(ps_perm, :patron_status_permission => {:visible => !ps_perm.visible}), :method => :put, :remote => true, :class => "toggle_visible" %></td>
      </tr>
      <% end %>
      <tr>
        <td colspan="4"><%= submit_tag "Save changes", :name => nil, data: { :remote => true } %></td>
      </tr>
		</tbody>
	</table>
	<% end %>
</div>

<div id="patron_status_permission_new_form">
  <%= render "patron_status_permissions/new" %>
</div>

<% end %>

app/views/patron_statuses/edit.html.erb
<h1>Editing patron status</h1>

<%= render 'form', :locals => { :disable_code_field => true }%>

<%= icon_tag :show %><%= link_to 'Show', @patron_status %> |
<%= icon_tag :back %>
<%= link_to 'Back', patron_statuses_path %>

app/views/patron_statuses/index.html.erb
<h1>Listing patron statuses</h1>

<%= form_tag patron_statuses_path, :class => "form-inline clearfix", :method => :get do %>
<%= render "common/searchbox" %>
<% end %>
<br />

<div id="patron_statuses">
<%= render "patron_statuses" %>
</div>

<br />

<%= icon_tag :add %><%= link_to 'New patron status', new_patron_status_path %>

app/views/patron_statuses/new.html.erb
<h1>New patron status</h1>

<%= render "form", :locals => { :disable_code_field => false } %>

<%= icon_tag :back %>
<%= link_to 'Back', patron_statuses_path %>

app/views/patron_statuses/show.html.erb
<h1><%= @patron_status.web_text %></h1>

<dl class="dl-horizontal">
<% if @patron_status.code? %>

  <dt>Code:</dt>
  <dd><%=h @patron_status.code %></dd>

<% end %>

<% if @patron_status.original_text? %>

  <dt>Original text:</dt>
  <dd><%=h @patron_status.original_text %></dd>

<% end %>
<% if @patron_status.web_text? %>

  <dt>Web text:</dt>
  <dd><%=h @patron_status.web_text.html_safe %></dd>

<% end %>
<% if @patron_status.keywords? %>

  <dt>Keywords:</dt>
  <dd><%=h @patron_status.keywords %></dd>

<% end %>
<% if @patron_status.description? %>

  <dt>Description:</dt>
  <dd><%=h @patron_status.description.html_safe %></dd>

<% end %>
<% if @patron_status.under_header? %>

  <dt>Grouping:</dt>
  <dd><%=h @patron_status.under_header.html_safe %></dd>

<% end %>
<% if @patron_status.id_type? %>

  <dt>ID Type:</dt>
  <dd><%=h @patron_status.id_type.html_safe %></dd>

<% end %>

  <dt>From Aleph?</dt>
  <dd><%=h @patron_status.from_aleph %>


  <dt>Permissions by Sub Library</dt>
  <dd>
    <%= form_tag patron_status_path, :class => "form-inline clearfix", :method => :get do %>
      <div class="row">
        <div class="col-sm-8">
        <%= select_tag 'sublibrary_code', options_for_select(@sublibraries.collect{ |s| [sublibrary_text(s), s.code] }, {:selected => params[:sublibrary_code]}),
          {prompt: "Select a sublibrary", class: 'form-control' }%>
        </div>
        <div class="col-sm-2">
          <button class="btn btn-default" type="submit">View permissions</button>
        </div>
      </div>
    <% end %>
  </dd>

</dl>
<div id="permissions_chart"><%= render "permissions" %></div>

<br />

<%= icon_tag :edit %><%= link_to 'Edit', edit_patron_status_path(@patron_status) %> |
<%= icon_tag :back %>
<%= link_to 'Back', patron_statuses_path %>