config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "admin" do
    resources :sublibraries
    resources :users
    resources :patron_status_permissions
    resources :permission_values
    resources :permissions
    resources :patron_statuses
    resources :application_details

    get 'clear_patron_data' => 'users#clear_patron_data'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    match '/logout', to: 'sessions#destroy', as: :logout, via: [:post]
    match '/login', to: 'users/omniauth_callbacks#passthru', as: :login, via: [:post]
  end

  patch 'permissions/update_order' => 'permissions#update_order'
  patch 'patron_status_permissions/update_multiple' => 'patron_status_permissions#update_multiple'

  get 'search' => 'privileges#search', as: :search
  get 'patrons/:id' => 'privileges#show_patron_status', as: :patron
  get 'patrons(.:format)' => 'privileges#index_patron_statuses', as: :patrons

  root to: 'privileges#index_patron_statuses'
end

app/models/sublibrary.rb
class Sublibrary < ApplicationRecord
  include Utilities::Common

  # Defines a scope of visible sublibraries where the web text is not null or blank and the visible flag is set to true
  scope :visible, ->{ where("sublibraries.web_text <> ? AND NOT(sublibraries.web_text IS NULL) and sublibraries.visible", "") }

  #Validations
  validates :code, presence: true, uniqueness: true
  validate :code_is_only_prefix
  validate :web_text_required_if_not_from_aleph

  # Required web_text if not from Aleph
  def web_text_required_if_not_from_aleph
    errors.add(:web_text, "can't be blank") if (!from_aleph and web_text.blank?)
  end
  
  # This makes sure the code is seen as blank if it just equals the namespace prefix
  def code_is_only_prefix
    errors.add(:code, "can't be blank") if (code == PrivilegesGuide::LOCAL_CREATION_PREFIX)
  end

  #Has many patron status permissions since they each have a sublibrary
  has_many :patron_status_permissions,
           primary_key: "code",
           foreign_key: "sublibrary_code",
           dependent: :destroy

  # The Sunspot searchable object
  searchable auto_index: Utilities::Common::index? do
    text :web_text, :original_text, :code, :under_header
    string :web_text, stored: true do
      (web_text.blank?) ? nil : web_text
    end
    string :code, stored: true
    boolean :visible, stored: true
    boolean :visible_frontend, stored: true do
      (!code.blank? && !web_text.blank? && visible)
    end
    boolean :from_aleph, stored: true
    string :original_text
    string :under_header, stored: true do
      (under_header.blank?) ? "Other NYU Libraries" : under_header
    end
    string :sort_header, stored: true do
      (under_header.blank?) ? "other nyu libraries" : under_header.downcase.gsub(/^nyu/, '!nyu')  # Force nyu to be first
    end
    # Strip tags to sort
    string :sort_text, stored: true do
      web_text.downcase.gsub(/<\/?[^>]*>/, "") unless web_text.nil?
    end
  end

end

app/controllers/sublibraries_controller.rb
class SublibrariesController < ApplicationController
  before_action :authenticate_admin

  # GET /sublibraries
  def index
    @sublibrary_search = sublibrary_search
  end

  # GET /sublibraries/1
  def show
    @sublibrary = Sublibrary.find(params[:id])
  end

  # GET /sublibraries/new
  def new
    @sublibrary = Sublibrary.new
  end

  # GET /sublibraries/1/edit
  def edit
    @sublibrary = Sublibrary.find(params[:id])
  end

  # POST /sublibraries
  def create
    @sublibrary = Sublibrary.new
    @sublibrary.code = "#{prefix}#{params[:sublibrary][:code]}"
    @sublibrary.web_text = params[:sublibrary][:web_text]
    @sublibrary.from_aleph = (params[:sublibrary][:from_aleph]) ? params[:sublibrary][:from_aleph] : false
    @sublibrary.under_header = params[:sublibrary][:under_header]

    respond_to do |format|
      if @sublibrary.save
        format.html { redirect_to @sublibrary, notice: t('sublibraries.create_success') }
      else
        # If failed, set the code back to user-entered code for rendering, without prefix
        @sublibrary.code = params[:sublibrary][:code]
        format.html { render action: "new" }
      end
    end
  end

  # PUT /sublibraries/1
  # PUT /sublibraries/1.js
  def update
    @sublibrary = Sublibrary.find(params[:id])
    @sublibraries = sublibrary_search.results

    respond_to do |format|
      if @sublibrary.update(sublibrary_params)
        flash[:notice] = t('sublibraries.update_success')
        format.html { redirect_to @sublibrary }
        format.js { render nothing: true } if request.xhr?
      else
        format.html { render action: "edit" }
        format.js { render nothing: true } if request.xhr?
      end
    end
  end

  # DELETE /sublibraries/1
  def destroy
    @sublibrary = Sublibrary.find(params[:id])
    @sublibrary.destroy

    respond_to do |format|
      format.html { redirect_to sublibraries_url, notice: t('sublibraries.destroy_success') }
    end
  end

  def sort_column
    super "Sublibrary", "sort_text"
  end
  helper_method :sort_column

  private
  def sublibrary_search
    @sublibrary_search ||= Privileges::Search::SublibrarySearch.new(**sublibrary_search_params)
  end

  def sublibrary_search_params
    params.permit(:q, :sort, :direction, :page).to_h.symbolize_keys.merge(admin_view: admin_view?)
  end

  def sublibrary_params
    if params[:sublibrary].present?
      params.require(:sublibrary).permit(:code, :web_text, :from_aleph, :under_header, :visible)
    else
      {}
    end
  end

  def prefix
    #This handles local creation of patron statuses by adding a namespace prefix, namely nyu_ag_noaleph_
    @prefix ||= (!params[:sublibrary][:from_aleph]) ? local_creation_prefix : ""
  end
end

app/helpers/sublibrary_helper.rb
module SublibraryHelper
  
  # Determine whether or not this @patron_status has access to the given sublibrary
  # * Return false if the sublibraries with access instance var is nil, that means there are no sublibraries this use has access to
  # * Return true if the current sublibrary is in the list of sublibraries this user has access to
  def access_to_sublibrary(sublibrary)
    (@sublibraries_with_access.nil?) ? false : (@sublibraries_with_access.include? sublibrary)
  end
  
  # Made a decision to print the sublibrary code if no web text is available
  def sublibrary_text(sublibrary)
    (sublibrary.web_text.empty?) ? sublibrary.code : sublibrary.web_text.html_safe
  end
  
  # Loop through grouped sublibraries to make optgroups for printing
  def grouped_sublibraries
    html = ""
    @sublibraries.keys.each do |sublibrary_group|
      html << content_tag(:optgroup, label: sublibrary_group) {
        @sublibraries[sublibrary_group].collect {|sublibrary|
         concat(content_tag(:option, "#{strip_tags(sublibrary.stored(:web_text))} #{!access_to_sublibrary(sublibrary.stored(:code)) ? '(no access)' : ''}", value: sublibrary.stored(:code), disabled: !access_to_sublibrary(sublibrary.stored(:code)), selected: sublibrary_selected(sublibrary)))
        }
      }
    end
    html
  end
  
  # Logic to decide if sublibrary option is selected
  # * True if sublibrary code exists and equals current selected param
  def sublibrary_selected(sublibrary)
    (!sublibrary.stored(:code).nil? && params[:sublibrary_code] == sublibrary.stored(:code))
  end

end

app/views/sublibraries/_form.html.erb
<%= form_for(@sublibrary) do |f| %>
<% if @sublibrary.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(@sublibrary.errors.count, "error") %> prohibited this sublibrary from being saved:</h2>

    <ul>
    <% @sublibrary.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="form-group">
    <%= f.label :code %>
    <%= f.text_field :code, class: 'form-control' %>
  </div>
  <% if @sublibrary.from_aleph? %>
    <div class="form-group">
      <%= f.label :original_text %>
      <%= f.text_field :original_text, :disabled => true, class: 'form-control' %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :web_text %>
    <%= f.text_field :web_text, class: 'form-control' %>
  </div>
 	<div class="form-group">
    <%= f.label :under_header, "Grouping" %>
    <%= f.text_field :under_header, class: 'form-control' %>
  </div>
  <div class="actions">
    <button class="btn btn-default" type="submit">Save changes</button>
  </div>
<% end %>

<br />

app/views/sublibraries/_sublibraries.html.erb
<p><%= page_entries_info_sunspot @sublibrary_search %></p>

<%= paginate @sublibrary_search.hits, theme: "bootstrap" %>

<table class="table table-bordered table-striped">
  <thead>
	  <tr>
  		<th><%= sortable "under_header", "Grouping"%></th>
  		<th><%= sortable "code"%></th>
  		<th><%= sortable "original_text"%></th>
  		<th><%= sortable "sort_text", "Web text"%></th>
  		<th><%= sortable "from_aleph", "From Aleph?"%></th>
  		<th colspan="4">Actions</th>
    </tr>
  </thead>
  <tbody>

<% @sublibrary_search.results.each do |sublibrary| %>
  <tr class="<%=hidden_class(sublibrary)%>">
	  <td><%=h sublibrary.under_header unless sublibrary.under_header.eql? sublibrary.web_text %></td>
    <td><%=h sublibrary.code %></td>
    <td><%=h sublibrary.original_text %></td>
    <td><%=h sublibrary.web_text.html_safe unless sublibrary.web_text.blank? %></td>
    <td><%=h sublibrary.from_aleph %></td>
    <td class="actions"><%= link_to 'Show', sublibrary %></td>
    <td class="actions"><%= link_to 'Edit', edit_sublibrary_path(sublibrary) %></td>
    <td class="actions"><%= link_to_unless(sublibrary.from_aleph?, 'Destroy', sublibrary, data: { confirm: 'Are you sure?' }, :method => :delete) %></td>
    <td class="actions"><%=
      link_to(
        "#{sublibrary.visible ? 'Hide' : 'Reveal'}",
        sublibrary_path(
          sublibrary,
          **params.permit(:controller, :action).to_h.symbolize_keys, sublibrary: { visible: !sublibrary.visible }
        ),
        method: :put, remote: true, class: "toggle_visible"
      )
    %></td>
  </tr>
<% end %>

  </tbody>
</table>

<%= paginate @sublibrary_search.hits, theme: "bootstrap" %>

app/views/sublibraries/edit.html.erb
<h1>Editing sub library</h1>

<%= render "form", :locals => { :disable_code_field => true }%>

<%= icon_tag :show %><%= link_to 'Show', @sublibrary %> |
<%= icon_tag :back %>
<%= link_to 'Back', sublibraries_path %>

app/views/sublibraries/index.html.erb
<h1>Listing sub libraries</h1>

<%= form_tag sublibraries_path, :class => "form-inline clearfix", :method => :get do %>
<%= render "common/searchbox" %>
<% end %>
<br />

<div id="sublibraries">
<%= render :partial => "sublibraries" %>
</div>

<br />

<%= icon_tag :add %><%= link_to 'New sub library', new_sublibrary_path %>

app/views/sublibraries/new.html.erb
<h1>New sublibrary</h1>

<%= render "form" %>

<%= icon_tag :back %>
<%= link_to 'Back', sublibraries_path %>

app/views/sublibraries/show.html.erb
<h1><%=h @sublibrary.web_text.html_safe %></h1>

<dl class="dl-horizontal">
  
<% if @sublibrary.from_aleph? %>
  <dt>Code:</dt>
  <dd><%=h @sublibrary.code %></dd>
  <dt>Original text:</dt>
  <dd><%=h @sublibrary.original_text %></dd>
<% end %>

  <dt>Web text:</dt>
  <dd><%=h @sublibrary.web_text.html_safe %></dd>

<% if @sublibrary.under_header? %>
  <dt>Grouping:</dt>
  <dd><%=h @sublibrary.under_header.html_safe %></dd>
<% end %>

  <dt>From Aleph?</dt>
  <dd><%=h @sublibrary.from_aleph %></dd>
  
</dl>

<%= icon_tag :edit %><%= link_to 'Edit', edit_sublibrary_path(@sublibrary) %> |
<%= icon_tag :back %>
<%= link_to 'Back', sublibraries_path %>