config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "admin" do
    resources :sublibraries
    resources :users
    resources :patron_status_permissions
    resources :permission_values
    resources :permissions
    resources :patron_statuses
    resources :application_details

    get 'clear_patron_data' => 'users#clear_patron_data'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    match '/logout', to: 'sessions#destroy', as: :logout, via: [:post]
    match '/login', to: 'users/omniauth_callbacks#passthru', as: :login, via: [:post]
  end

  patch 'permissions/update_order' => 'permissions#update_order'
  patch 'patron_status_permissions/update_multiple' => 'patron_status_permissions#update_multiple'

  get 'search' => 'privileges#search', as: :search
  get 'patrons/:id' => 'privileges#show_patron_status', as: :patron
  get 'patrons(.:format)' => 'privileges#index_patron_statuses', as: :patrons

  root to: 'privileges#index_patron_statuses'
end

app/models/permission.rb
class Permission < ApplicationRecord
  include Utilities::Common

  # Validations
  validates :code, presence: true, uniqueness: true
  validate :web_text_required_if_not_from_aleph
  validate :code_is_only_prefix
  validate :increment_sort_order

  # Required web_text if not from Aleph
  def web_text_required_if_not_from_aleph; errors.add(:web_text, "can't be blank") if (!from_aleph and web_text.blank?); end
  # This makes sure the code is seen as blank if it just equals the namespace prefix
  def code_is_only_prefix; errors.add(:code, "can't be blank") if (code == PrivilegesGuide::LOCAL_CREATION_PREFIX); end
  # Incremement sort order by one
  def increment_sort_order; self.sort_order ||= Permission.maximum("sort_order").to_i + 1; end

  # Has many possible permissions values
  has_many :permission_values,
           primary_key: "code",
           foreign_key: "permission_code",
           dependent: :destroy

  # Has many patron status permissions linked by the permission values they contain
  has_many :patron_status_permissions,
           through: :permission_values

  # Has many patron statuses linked by the patron sttatus permissions it contains
  has_many :patron_statuses,
           through: :patron_status_permissions

  # Named scopes
  scope :by_sort_order, ->{ order 'sort_order ASC, web_text ASC' }
  scope :visible, ->{ where visible: 1 }

end

app/controllers/permissions_controller.rb
# This controller handles the permissions assigned to sublibraries
# each permission has a set of possible values (PermissionValues)
class PermissionsController < ApplicationController
  before_action :authenticate_admin

  # GET /permissions
  def index
    @permissions = Permission.by_sort_order
  end

  # GET /permissions/1
  def show
    @permission = Permission.find(params[:id])
    @permission_values = PermissionValue.where(permission_code: @permission.code)
    @permission_value = PermissionValue.new
  end

  # GET /permissions/new
  def new
    @permission = Permission.new
  end

  # GET /permissions/1/edit
  def edit
    @permission = Permission.find(params[:id])
  end

  # POST /permissions
  def create
    @permission = Permission.new
    @permission.code = "#{prefix}#{params[:permission][:code]}"
    @permission.web_text = params[:permission][:web_text]
    @permission.from_aleph = (params[:permission][:from_aleph]) ? params[:permission][:from_aleph] : false

    respond_to do |format|
      if @permission.save
        flash[:notice] = t("permissions.create_success")
        format.html { redirect_to(@permission) }
      else
        #If failed, set the code back to user-entered code, without prefix
	      @permission.code = params[:permission][:code]
        format.html { render action: "new" }
      end
    end
  end

  # PUT /permissions/1
  # PUT /permissions/1.js
  def update
    @permission = Permission.find(params[:id])
    @permissions = Permission.by_sort_order

    respond_to do |format|
      if @permission.update_attributes(permission_params)
        flash[:notice] = t("permissions.update_success")
        format.html { redirect_to(@permission) }
        format.js { render nothing: true } if request.xhr?
      else
        flash[:danger] = t("permissions.update_failure")
        format.html { render action: "edit" }
        format.js { render nothing: true } if request.xhr?
      end
    end
  end

  # PUT /permissions/update_order
  # PUT /permissions/update_order.js
  def update_order
    if params[:permissions]
      params[:permissions].each_with_index do |id, index|
        Permission.find(id).update(sort_order: index+1)
      end
    end
    respond_to do |format|
      format.html { redirect_to permissions_url, notice: t("permissions.update_order_success") and return }
      format.js { render layout: false } if request.xhr?
    end
  end

  # DELETE /permissions/1
  def destroy
    @permission = Permission.find(params[:id])
    @permission.destroy

    respond_to do |format|
      format.html { redirect_to permissions_url, notice: t("permissions.delete_succes") }
    end
  end

  private
  def permission_params
    if params[:permission].present?
      params.require(:permission).permit(:code, :from_aleph, :visible, :web_text)
    else
      {}
    end
  end

  def prefix
    #This handles local creation of patron statuses by adding a namespace prefix, namely nyu_ag_noaleph_
    @prefix ||= (!params[:permission][:from_aleph].nil?) ? local_creation_prefix : ""
  end
end

app/views/permissions/_form.html.erb
<%= form_for(@permission) do |f| %>
  <% if @permission.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@permission.errors.count, "error") %> prohibited this record from being saved:</h2>
      <ul>
      <% @permission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :code %>
    <%= f.text_field :code, :disabled => locals[:disable_code_field], class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :web_text %>
    <%= f.text_field :web_text, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-default">Save changes</button>
  </div>
<% end %>

app/views/permissions/_permissions.html.erb
<%= form_tag({:controller => "permissions", :action => "update_order"}, :method => :patch, :remote => true) do %>

  <ul id="edit_permissions_list" class="sortable_list">

  <% @permissions.each do |permission| %>

  	<%= content_tag_for :li, permission do %>
  	  <%= hidden_field_tag "permissions[]", permission.id %>
      <h4 id="permission_span_<%=permission.id%>" class="permission_header <%=hidden_class(permission)%>"><i class="glyphicon glyphicon-move"></i>&nbsp;<%=h permission.web_text %></h4>
      <%= link_to 'Show', permission %> |
      <%= link_to 'Edit', edit_permission_path(permission) %> |
      <%= link_to_unless permission.from_aleph?, "Destroy", permission, :data => { :confirm =>'Are you sure?' }, :method => :delete%> |
      <%= link_to permission_path(permission, :permission => {:visible => !permission.visible}), :method => :put, :remote => true, :class => "toggle_visible" do %>
          <%= (permission.visible?) ? "Hide" : "Reveal" %>
        <% end %>
  	<% end %>

  <% end %>

  </ul>

  <button class="btn btn-default" type="submit" data-remote="true">Save changes</button>

<% end %>

app/views/permissions/_show.html.erb
<h1><%= @permission.web_text%></h1>

<dl class="dl-horizontal">
  
  <dt>Code:</dt>
  <dd><%=h @permission.code %></dd>

  <dt>Web text:</dt>
  <dd><%=h @permission.web_text %></dd>

  <dt>From Aleph?</dt>
  <dd><%=h @permission.from_aleph %></dd>

</dl>

<h3>Permission Values:</h3>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
    	<th>Code</th>
    	<th>Web text</th>
    	<th>From Aleph?</th>
    	<th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @permission_values.each do |pv| %>
    <tr class="<%=cycle("even","odd") %>">
  	<td><%= pv.code %></td>
  	<td><%= pv.web_text.html_safe %></td>
  	<td><%= pv.from_aleph %></td>
  	<!--td><%= link_to 'Show', pv %></td-->
  	<td><%= link_to 'Edit', edit_permission_value_path(pv) %></td>
  	<td><%= link_to_unless(pv.from_aleph?, 'Destroy', pv, :data => { :confirm =>'Are you sure?' }, :method => :delete) %></td>
  </tr>
  <% end %>
  </tbody>
</table>


<%= render "permission_values/new" %>

<br />

<%= icon_tag :edit %><%= link_to 'Edit', edit_permission_path(@permission) %> |
<%= icon_tag :back %>
<%= link_to 'Back', permissions_path %>

app/views/permissions/edit.html.erb
<h1>Editing permission</h1>

<%= render 'form', :locals => { :disable_code_field => true }%>

<%= icon_tag :show %><%= link_to 'Show', @permission %> |
<%= icon_tag :back %>
<%= link_to 'Back', permissions_path %>

app/views/permissions/index.html.erb
<h1>Listing permissions</h1>

<blockquote id="permissions">
  <%= render "permissions" %>
</blockquote>

<br />

<%= icon_tag :add %>
<%= link_to 'New permission', new_permission_path %>

app/views/permissions/new.html.erb
<h1>New permission</h1>

<%= render 'form', :locals => { :disable_code_field => false }%>

<%= icon_tag :back %>
<%= link_to 'Back', permissions_path %>

app/views/permissions/show.html.erb
<%= render :partial => "show" %>

app/views/permissions/update_order.js.erb
$(".flash_messages").html("<div class=\"alert alert-success\"><%= t('permissions.update_order_success')%><a class=\"close\" data-dismiss=\"alert\" href=\"#\">×</a></div>");