config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "admin" do
    resources :sublibraries
    resources :users
    resources :patron_status_permissions
    resources :permission_values
    resources :permissions
    resources :patron_statuses
    resources :application_details

    get 'clear_patron_data' => 'users#clear_patron_data'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    match '/logout', to: 'sessions#destroy', as: :logout, via: [:post]
    match '/login', to: 'users/omniauth_callbacks#passthru', as: :login, via: [:post]
  end

  patch 'permissions/update_order' => 'permissions#update_order'
  patch 'patron_status_permissions/update_multiple' => 'patron_status_permissions#update_multiple'

  get 'search' => 'privileges#search', as: :search
  get 'patrons/:id' => 'privileges#show_patron_status', as: :patron
  get 'patrons(.:format)' => 'privileges#index_patron_statuses', as: :patrons

  root to: 'privileges#index_patron_statuses'
end

app/models/utilities/common.rb
module Utilities
  module Common
    class << self
    
      # Determine if the current process is running from a rake task
      # This is decided by seeing if the pid file exists.
      def running_from_rake? rake_pid_file = "tmp/pids/load_aleph.pid"
        @running_from_rake ||= File.exists? File.join(Rails.root, rake_pid_file)
      end
    
      # Alias for negation of running from rake 
      # Semantic choice for title made because models should not be auto-indexed from rake
      def index?
        !running_from_rake?
      end
    
   end 
  end
end

app/views/common/_flash_msg.html.erb
<div class="flash_messages">
  <% [:success, :notice, :error, :alert, :danger].each do |type| %>
    <%- alert_class = type == :notice ? 'info' : type %>
    <% if flash[type] %>
      <div class="alert alert-<%=alert_class%>"><%= flash[type] %>
         <a class="close" data-dismiss="alert" href="#">x</a>
      </div>
    <% end %>
  <% end %>
</div>

app/views/common/_modal.html.erb
<div class="modal-container">
  <div class="modal hide fade" id="ajax-modal" tabindex="-1">
  </div>
</div>

app/views/common/_prepend_body.html.erb
<%= render "common/modal" %>

app/views/common/_searchbox.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<div class="input-group col-sm-8">
  <label for="q" class="sr-only">Search...</label>
  <input autofocus="autofocus" class="search_q q form-control" id="q" name="q" placeholder="Search..." type="text">
  <span class="input-group-btn">
    <button type="submit" class="btn btn-primary search-btn form-control" id="search">
      <span class="submit-search-text">Search</span>
      <span class="glyphicon glyphicon-search"></span>
    </button>
  </span>
</div>

app/views/common/_sidebar.html.erb
<% if is_admin? %>
<%= sidebar_section("admin_panel", content_tag(:h2, "Admin Panel"), true) do %>
    <ul class="admin_options">
        <li><%= link_to "Manage Users", users_url %></li>
        <li><%= link_to "Manage Patron Statuses", patron_statuses_url %></li>
        <li><%= link_to "Manage Sublibraries", sublibraries_url %></li>
        <li><%= link_to "Manage Permissions", permissions_url %></li>
        <li><%= link_to "Manage Application Text", application_details_url %></li>
    </ul>
<% end -%>
<% end %>

<nav class="navbar navbar-default">
  <div id="intro_text" class="navbar-collapse sidebar-section" aria-expanded="true">
    <ul>
      <li><%= get_formatted_detail('intro_text')%></li>
    </ul>
  </div>
</nav>